# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Seknova-Practice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Seknova-Practice
  pod 'RealmSwift', '10.30.0'
  pod 'Charts' , '4.1.0'
  pod 'IQKeyboardManagerSwift', '6.5.10'
  pod 'BatteryView', '1.3.9'
  
  
  target 'Seknova-PracticeTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  target 'Seknova-PracticeUITests' do
    # Pods for testing
  end
  
end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
               end
          end
   end
end
